// <auto-generated />
using System;
using BankingData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace bankingapplication.Migrations
{
    [DbContext(typeof(BankingContext))]
    partial class BankingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountManagement.Account", b =>
                {
                    b.Property<int>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("accountId"));

                    b.Property<string>("_password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password");

                    b.Property<string>("accountType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("accountId");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasDiscriminator<string>("accountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Checkbooks.Checkbook", b =>
                {
                    b.Property<int>("checkbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("checkbookId"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payee")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("accountNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("routingNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("userAccountId")
                        .HasColumnType("int");

                    b.HasKey("checkbookId");

                    b.HasIndex("userAccountId");

                    b.ToTable("CheckbookRecords");
                });

            modelBuilder.Entity("Request.ServiceRequest", b =>
                {
                    b.Property<int>("serviceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceRequestId"));

                    b.Property<bool?>("accepted")
                        .HasColumnType("bit");

                    b.Property<long>("accountNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("dateResponded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("requestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("requestor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("userAccountId")
                        .HasColumnType("int");

                    b.HasKey("serviceRequestId");

                    b.HasIndex("userAccountId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("Transactions.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("accName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("accountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("userAccountId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userAccountId");

                    b.ToTable("TransactionRecords");
                });

            modelBuilder.Entity("AccountManagement.AdminAccount", b =>
                {
                    b.HasBaseType("AccountManagement.Account");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("AccountManagement.UserAccount", b =>
                {
                    b.HasBaseType("AccountManagement.Account");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("accBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("accName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("accountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("homeAddress")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<long>("routingNumber")
                        .HasColumnType("bigint");

                    b.HasIndex("accountNumber")
                        .IsUnique()
                        .HasFilter("[accountNumber] IS NOT NULL");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Checkbooks.Checkbook", b =>
                {
                    b.HasOne("AccountManagement.UserAccount", null)
                        .WithMany("Checkbook")
                        .HasForeignKey("userAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Request.ServiceRequest", b =>
                {
                    b.HasOne("AccountManagement.UserAccount", null)
                        .WithMany("serviceRequests")
                        .HasForeignKey("userAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transactions.Transaction", b =>
                {
                    b.HasOne("AccountManagement.UserAccount", null)
                        .WithMany("transactions")
                        .HasForeignKey("userAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccountManagement.UserAccount", b =>
                {
                    b.Navigation("Checkbook");

                    b.Navigation("serviceRequests");

                    b.Navigation("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
